language: java
jdk:
 - openjdk8

services:
  - docker

before_install:
  - docker-compose -f docker/dev/docker-compose.yml up -d

script:
  # the following command line builds the project, runs the tests
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install

after_script:
  - docker-compose -f docker/dev/docker-compose.yml stop
  - docker-compose -f docker/dev/docker-compose.yml rm -f