language: java
jdk:
 - openjdk8

services:
  - docker

before_install:
  - docker-compose -f docker/dev/docker-compose.yml up -d
  - cd src

script:
  # the following command line builds the project, runs the tests
  - mvn clean install -Ptest-business 

after_script:
  - docker-compose -f docker/dev/docker-compose.yml stop
  - docker-compose -f docker/dev/docker-compose.yml rm -f